name:                euler
version:             1.0.0
github:              "jchristensen/euler"
license:             MIT
author:              "Justin Christensen"
maintainer:          "wroathe@gmail.com"
copyright:           "Justin Christensen <wroathe@gmail.com>"

extra-source-files:
- ./*.md

description: Please see the README on Github at <https://github.com/jchristensen/euler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
    - arithmoi

_ghc_options: &ghc_opts
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

_exe_options: &exe_opts
  <<: *ghc_opts
  main: Main.hs
  dependencies:
  - euler

executables:
  problem1:
    <<: *exe_opts
    source-dirs: app/Problem1
  problem2:
    <<: *exe_opts
    source-dirs: app/Problem2
  problem3:
    <<: *exe_opts
    source-dirs: app/Problem3
  problem4:
    <<: *exe_opts
    source-dirs: app/Problem4
  problem5:
    <<: *exe_opts
    source-dirs: app/Problem5

tests:
  spec:
    <<: *ghc_opts
    main:                EulerSpec.hs
    source-dirs:         test
    dependencies:
    - euler
    - hspec

benchmarks:
  palindromes:
    <<: *ghc_opts
    main:                Palindromes.hs
    source-dirs:         bench
    dependencies:
    - euler
    - criterion
